env:
  browser: true
  es6: true
  node: true
  meteor: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'prettier'
  - 'prettier/react'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jsx-a11y
rules:
  no-console: 0
  react/prop-types: 0
  no-unused-vars: 1
